<?php

add_action( 'init', function() {
	register_post_type( 'question', array(
	'labels' => array(
		'name' => 'Questions',
		'singular_name' => 'Question',
		'menu_name' => 'Question',
		'all_items' => 'All Question',
		'edit_item' => 'Edit Question',
		'view_item' => 'View Question',
		'view_items' => 'View Question',
		'add_new_item' => 'Add New Question',
		'new_item' => 'New Question',
		'parent_item_colon' => 'Parent Question:',
		'search_items' => 'Search Question',
		'not_found' => 'No question found',
		'not_found_in_trash' => 'No question found in Trash',
		'archives' => 'Question Archives',
		'attributes' => 'Question Attributes',
		'insert_into_item' => 'Insert into question',
		'uploaded_to_this_item' => 'Uploaded to this question',
		'filter_items_list' => 'Filter question list',
		'filter_by_date' => 'Filter question by date',
		'items_list_navigation' => 'Question list navigation',
		'items_list' => 'Question list',
		'item_published' => 'Question published.',
		'item_published_privately' => 'Question published privately.',
		'item_reverted_to_draft' => 'Question reverted to draft.',
		'item_scheduled' => 'Question scheduled.',
		'item_updated' => 'Question updated.',
		'item_link' => 'Question Link',
		'item_link_description' => 'A link to a question.',
	),
	'public' => true,
	'show_in_rest' => true,
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'quiz', array(
	'labels' => array(
		'name' => 'Quizzes',
		'singular_name' => 'Quiz',
		'menu_name' => 'Quiz',
		'all_items' => 'All Quiz',
		'edit_item' => 'Edit Quizzes',
		'view_item' => 'View Quizzes',
		'view_items' => 'View Quiz',
		'add_new_item' => 'Add New Quizzes',
		'new_item' => 'New Quizzes',
		'parent_item_colon' => 'Parent Quizzes:',
		'search_items' => 'Search Quiz',
		'not_found' => 'No quiz found',
		'not_found_in_trash' => 'No quiz found in Trash',
		'archives' => 'Quizzes Archives',
		'attributes' => 'Quizzes Attributes',
		'insert_into_item' => 'Insert into quizzes',
		'uploaded_to_this_item' => 'Uploaded to this quizzes',
		'filter_items_list' => 'Filter quiz list',
		'filter_by_date' => 'Filter quiz by date',
		'items_list_navigation' => 'Quiz list navigation',
		'items_list' => 'Quiz list',
		'item_published' => 'Quizzes published.',
		'item_published_privately' => 'Quizzes published privately.',
		'item_reverted_to_draft' => 'Quizzes reverted to draft.',
		'item_scheduled' => 'Quizzes scheduled.',
		'item_updated' => 'Quizzes updated.',
		'item_link' => 'Quizzes Link',
		'item_link_description' => 'A link to a quizzes.',
	),
	'public' => true,
	'show_in_rest' => true,
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
	),
	'delete_with_user' => false,
) );
} );
